# Site settings
title: Vocal Cataclysm
email: justin.rabensdorf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jrabef.github.io" # the base hostname & protocol for your site
twitter_username: soulkarver
github_username:  jrabef
safe: true
lsi: false
source: jrabef.github.io

# Build settings
encoding: utf-8
markdown: kramdown