# Site settings
title: Vocal Cataclysm
email: justin.rabensdorf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on various technologies, literature, and music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jrabef.github.io" # the base hostname & protocol for your site
twitter_username: soulkarver
github_username:  jrabef
safe: true
lsi: false
source: jrabef.github.io

# Build settings
encoding: utf-8
markdown: kramdown